# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SiLab
email: houman@neurovascular.ca
description: > # this means to ignore newlines until "baseurl:"
  SiLab (Stroke Innovation Lab) is the lab website of Dr. Khosravani, highlighting our initiatives, projects, and blog site related to stroke and critical care/neurocritical care.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://neuroccm.org" # the base hostname & protocol for your site
twitter_username: neuroccm
github_username:  neuroccm

# Build settings
markdown: kramdown

# Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
#
#comments :
#  provider : disqus
#  disqus :
#    short_name : neuroccm
#  livefyre :
#    site_id : 123
#  intensedebate :
#    account : 123abc
#  facebook :
#    appid : 123
#    num_posts: 5
#    width: 580
#    colorscheme: light



# Other items of interest:
# logo: img/logo-2x.png
# timezone: America/Los_Angeles
# gauges_id: 503c5af6613f5d0f19000027
# google_analytics_id: UA-50755011-1
# google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY
